### ISSUE TITLE
chatbot_for_movies/notebooks/.ipynb_checkpoints/TF_Chatbot_prototipo_v3-checkpoint.ipynb

### ISSUE THREAD

**Issue by kpkrima** [douglasdcm/chatbot_for_movies#6]
**this was the file location** 
chatbot_for_movies/notebooks/.ipynb_checkpoints/TF_Chatbot_prototipo_v3-checkpoint.ipynb

**![chatbot](https://user-images.githubusercontent.com/79370041/129088294-0f42767f-92f1-4116-b85d-652f3cc9bdd3.png) in line** 

conversation = get_the_next_conversation(conversations)
conversation

**error**

**Comment by douglasdcm** [comment]
I got it. You need to use the notebooks in 001, 002, 

Here you have the instructions to retrain the chatbot

Attention
This chat bot was developed using WSL Ubuntu, so it is not guaranteed to work on different environment.
To retrain the chat bot it is necessary to use the notebooks following the order of the files 001, 002... and maybe the notebooks will need to be adapted dependin on your dataset.
The notebooks generate the 3 datasets used by the chat bot: movie_lines_pre_processed_for_test.tvs, page_rank_questions.txt and page_rank_answers.txt. If retraining, get the generated files in notebooks/chatdata and put in src/chatdata.
The model.h5 and the tokenizer.pickle are also generated by the notebooks and it is needed to copy both in src/chatdata.
This chat bot was developed using 30000 messages due to performance issues, so pay attention to your dataset if you are retrainign the chat bot.

![image](https://user-images.githubusercontent.com/29078346/129091134-a11836dd-032a-41ac-8cb2-9e3ad814eb56.png)
